version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

  attacks:
    image: python:3.11.4
    build: attacks
    volumes:
      - ./attacks/:/attacks/
    command: python /attacks/http_flood.py
